muge:
  profiles:
    - name: a
      parameters:
        b: 1
        c: 2
      clients:
        - e
        - h
    - name: d
      parameters:
        b: 89
        c: 4
      clients:
        - f
        - gg
