muge:
  profiles:
    - name: a
      parameters:
        b: 1
        c: 2
      clients:
        - e
        - f
    - name: d
      parameters:
        b: 3
        c: 4
      clients:
        - g
